PUT  http://localhost:8080/hemograma/1
Content-Type: application/json

{
        "Hemacias": 999,
        "Hemoglobina": 999,
        "Hematocritos": 999,
        "Leucocitos": 999,
        "VGM": 999,
        "HGM": 999,
        "CHGM": 999,
        "RDW": 999,
        "Plaquetas": 111
}